//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfessionBot.res.strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class confessionbot_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal confessionbot_strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfessionBot.res.strings.confessionbot-strings", typeof(confessionbot_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have failed too many attempts. Aborting..
        /// </summary>
        internal static string ConfessionBotAmbiguityFail {
            get {
                return ResourceManager.GetString("ConfessionBotAmbiguityFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confession aborted!.
        /// </summary>
        internal static string ConfessionBotConfessionAborted {
            get {
                return ResourceManager.GetString("ConfessionBotConfessionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server selection failed too many attempts..
        /// </summary>
        internal static string ConfessionBotConfessionFailed {
            get {
                return ResourceManager.GetString("ConfessionBotConfessionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confession sent!.
        /// </summary>
        internal static string ConfessionBotConfessionSent {
            get {
                return ResourceManager.GetString("ConfessionBotConfessionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confession.
        /// </summary>
        internal static string ConfessionBotConfessionTitle {
            get {
                return ResourceManager.GetString("ConfessionBotConfessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfessionBot is a bot for publishing anonymous confessions in a Discord server. The server may optionally log your confessions, typically for moderating and law-enforcement purposes,in which case the author is hidden with spoilers until that information is necessary. In order to confess to the server using the bot, send the bot a direct message starting with &quot;confess&quot; followed by your confession (without any prefix or quotation marks)..
        /// </summary>
        internal static string ConfessionBotInfoDescription {
            get {
                return ResourceManager.GetString("ConfessionBotInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confession Bot Info.
        /// </summary>
        internal static string ConfessionBotInfoTitle {
            get {
                return ResourceManager.GetString("ConfessionBotInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response..
        /// </summary>
        internal static string ConfessionBotInvalidResponse {
            get {
                return ResourceManager.GetString("ConfessionBotInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have more than one mutual servers..
        /// </summary>
        internal static string ConfessionBotMultipleMutualServers {
            get {
                return ResourceManager.GetString("ConfessionBotMultipleMutualServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot was unable to find mutual servers. This is usually caused by a Discord bug, which is typically solved by simply restarting your own Discord client and then trying again..
        /// </summary>
        internal static string ConfessionBotNoMutualServer {
            get {
                return ResourceManager.GetString("ConfessionBotNoMutualServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select a server from the following list, please reply with the preceding number (no period)..
        /// </summary>
        internal static string ConfessionBotSelectServer {
            get {
                return ResourceManager.GetString("ConfessionBotSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply with 1 if you wish to specify a server, 2 if you wish to confess to all servers, or 3 to abort..
        /// </summary>
        internal static string ConfessionBotServerAmbiguity {
            get {
                return ResourceManager.GetString("ConfessionBotServerAmbiguity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to obtain the source code at https://github.com/GoodGirlErica/ConfessionBot.
        /// </summary>
        internal static string ConfessionBotSource {
            get {
                return ResourceManager.GetString("ConfessionBotSource", resourceCulture);
            }
        }
    }
}
